[package]
name = "inkstone-bytecode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
bitflags = "1.3"
enum-ordinalize = "3.1"
smol_str = "0.1.18"
