[package]
name = "inkstone-bytecode"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
slab = "0.4.5"
integer-encoding = "3"
num_enum = "0.5"
