[package]
name = "inkstone-syn"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "4.6.1"
logos = "0.12.0"
num_enum = "0.5.4"
rowan = "0.14.0"
